"""seed in games and categories

Revision ID: 1960829b2ca6
Revises: 28da83d65df1
Create Date: 2025-08-18 23:56:55.970846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import table, column, Integer, String

# revision identifiers, used by Alembic.
revision: str = '1960829b2ca6'
down_revision: Union[str, Sequence[str], None] = '28da83d65df1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    games_table = table(
        "games",
        column("id", Integer),
        column("name", String),
        column("slug", String),
    )

    categories_table = table(
        "categories",
        column("id", Integer),
        column("name", String),
        column("slug", String),
        column("game_id", Integer),
    )

    # игры
    op.bulk_insert(
        games_table,
        [
            {"id": 1, "name": "Path of Exile 2", "slug": "poe2"},
            {"id": 2, "name": "Final Fantasy XIV", "slug": "ffxiv"},
            {"id": 3, "name": "Destiny 2", "slug": "destiny2"},
        ],
    )

    # категории
    op.bulk_insert(
        categories_table,
        [
            {"id": 1, "name": "Currency", "slug": "currency", "game_id": 1},
            {"id": 3, "name": "Unique", "slug": "unique", "game_id": 1},
            {"id": 4, "name": "Map", "slug": "map", "game_id": 1},

            {"id": 5, "name": "Weapon", "slug": "weapon", "game_id": 2},
            {"id": 6, "name": "Gear", "slug": "gear", "game_id": 2},
            {"id": 7, "name": "General", "slug": "general", "game_id": 2},
            {"id": 8, "name": "Mount", "slug": "mount", "game_id": 2},

            {"id": 9, "name": "Exotic", "slug": "exotic", "game_id": 3},
            {"id": 11, "name": "Shader", "slug": "shader", "game_id": 3},
            {"id": 12, "name": "General", "slug": "general", "game_id": 3},
        ],
    )

    # --- autogenerated schema changes ---
    op.create_table(
        'item_categories',
        sa.Column('item_id', sa.Integer(), nullable=False),
        sa.Column('category_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('item_id', 'category_id')
    )

    # меняем таблицу items через batch_alter_table
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.drop_index("ix_items_category_id")
        batch_op.drop_column("category_id")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('category_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'items', 'categories', ['category_id'], ['id'])
    op.create_index(op.f('ix_items_category_id'), 'items', ['category_id'], unique=False)
    op.drop_table('item_categories')
    # ### end Alembic commands ###
    op.execute("DELETE FROM categories WHERE id IN (1,3,4,5,6,7,8,9,11,12)")
    op.execute("DELETE FROM games WHERE id IN (1,2,3)")
