"""add avatar_url to users

Revision ID: 2906590e520c
Revises: 6e48b5f1a25c
Create Date: 2025-08-13 22:53:12.006153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2906590e520c'
down_revision: Union[str, Sequence[str], None] = '6e48b5f1a25c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=255), nullable=False))
    # ### end Alembic commands ###
