"""add categories_items table

Revision ID: 5bc7f4e2503e
Revises: e56a7eff1b25
Create Date: 2025-08-18 17:17:22.386888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bc7f4e2503e'
down_revision: Union[str, Sequence[str], None] = 'e56a7eff1b25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('category', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'category')
    # ### end Alembic commands ###
