"""users-name

Revision ID: 5fe17c7cb790
Revises: c3a38fcea02e
Create Date: 2025-08-13 22:01:31.954447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fe17c7cb790'
down_revision: Union[str, Sequence[str], None] = 'c3a38fcea02e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


from alembic import op
import sqlalchemy as sa
from sqlalchemy import text

def upgrade():
    # 1) добавляем колонку как nullable с временным default, чтобы SQLite пропустил
    with op.batch_alter_table('users') as b:
        b.add_column(sa.Column('name', sa.String(255), nullable=True, server_default=''))

    # 2) бэконаполняем (пример: префикс до @ из email)
    conn = op.get_bind()
    conn.execute(text(
        "UPDATE users SET name = COALESCE(NULLIF(name, ''), "
        "CASE WHEN instr(email, '@')>1 THEN substr(email,1,instr(email,'@')-1) ELSE email END)"
    ))

    # 3) снимаем server_default и делаем NOT NULL
    with op.batch_alter_table('users') as b:
        b.alter_column('name',
                       existing_type=sa.String(255),
                       nullable=False,
                       server_default=None)



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
